#!/bin/bash


# Runs program with nsjail


LANGUAGE=$1
PROGRAM_DIR=$2
NSJAIL="nsjail -Mo --log /dev/null --rlimit_nproc 40 --chroot / -- "


case $LANGUAGE in
	"bash")
		$NSJAIL /bin/bash $PROGRAM_DIR/program < $PROGRAM_DIR/testinput
		;;
	"ruby")
		$NSJAIL /usr/bin/ruby $PROGRAM_DIR/program < $PROGRAM_DIR/testinput
		;;
	"python")
		$NSJAIL /usr/local/bin/python3 $PROGRAM_DIR/program < $PROGRAM_DIR/testinput
		;;
	"c")
		mv $PROGRAM_DIR/program $PROGRAM_DIR/program.c # gcc requires .c extension
		/usr/bin/gcc $PROGRAM_DIR/program.c -o $PROGRAM_DIR/program.out
		$NSJAIL $PROGRAM_DIR/program.out < $PROGRAM_DIR/testinput
		;;
	"c++")
		mv $PROGRAM_DIR/program $PROGRAM_DIR/program.cc # g++ requires .cc extension
		/usr/bin/g++ -std=c++1y $PROGRAM_DIR/program.cc -o $PROGRAM_DIR/program.out
		$NSJAIL $PROGRAM_DIR/program.out < $PROGRAM_DIR/testinput
		;;
	*)
		echo "Unknown language."
esac

